package com.mingrui.flux.pojo;

import com.influxdb.annotations.Column;
import com.influxdb.annotations.Measurement;

import java.util.Date;

@Measurement(name = "abnormal_data")
public class AbnormalData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abnormal_data.id
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    @Column(tag = true)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abnormal_data.type
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abnormal_data.device_id
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    @Column(tag = true)
    private String deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abnormal_data.mn
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    @Column(tag = true)
    private String mn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abnormal_data.error_desc
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    private String errorDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abnormal_data.owner
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abnormal_data.status
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abnormal_data.owner_name
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    private String ownerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abnormal_data.user_id
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    @Column(tag = true)
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abnormal_data.address
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abnormal_data.locale_id
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    @Column(tag = true)
    private String localeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abnormal_data.record_at
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    private Long recordAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abnormal_data.handle_at
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    private Long handleAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abnormal_data.abnormal_date
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    private Date abnormalDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abnormal_data.process_date
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    private Date processDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abnormal_data.process_user_id
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    private String processUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abnormal_data.process_reason
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    private String processReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abnormal_data.created_at
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abnormal_data.updated_at
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abnormal_data.id
     *
     * @return the value of abnormal_data.id
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abnormal_data.id
     *
     * @param id the value for abnormal_data.id
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abnormal_data.type
     *
     * @return the value of abnormal_data.type
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abnormal_data.type
     *
     * @param type the value for abnormal_data.type
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abnormal_data.device_id
     *
     * @return the value of abnormal_data.device_id
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abnormal_data.device_id
     *
     * @param deviceId the value for abnormal_data.device_id
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abnormal_data.mn
     *
     * @return the value of abnormal_data.mn
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public String getMn() {
        return mn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abnormal_data.mn
     *
     * @param mn the value for abnormal_data.mn
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setMn(String mn) {
        this.mn = mn == null ? null : mn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abnormal_data.error_desc
     *
     * @return the value of abnormal_data.error_desc
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public String getErrorDesc() {
        return errorDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abnormal_data.error_desc
     *
     * @param errorDesc the value for abnormal_data.error_desc
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setErrorDesc(String errorDesc) {
        this.errorDesc = errorDesc == null ? null : errorDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abnormal_data.owner
     *
     * @return the value of abnormal_data.owner
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abnormal_data.owner
     *
     * @param owner the value for abnormal_data.owner
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abnormal_data.status
     *
     * @return the value of abnormal_data.status
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abnormal_data.status
     *
     * @param status the value for abnormal_data.status
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abnormal_data.owner_name
     *
     * @return the value of abnormal_data.owner_name
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public String getOwnerName() {
        return ownerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abnormal_data.owner_name
     *
     * @param ownerName the value for abnormal_data.owner_name
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName == null ? null : ownerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abnormal_data.user_id
     *
     * @return the value of abnormal_data.user_id
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abnormal_data.user_id
     *
     * @param userId the value for abnormal_data.user_id
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abnormal_data.address
     *
     * @return the value of abnormal_data.address
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abnormal_data.address
     *
     * @param address the value for abnormal_data.address
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abnormal_data.locale_id
     *
     * @return the value of abnormal_data.locale_id
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public String getLocaleId() {
        return localeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abnormal_data.locale_id
     *
     * @param localeId the value for abnormal_data.locale_id
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setLocaleId(String localeId) {
        this.localeId = localeId == null ? null : localeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abnormal_data.record_at
     *
     * @return the value of abnormal_data.record_at
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public Long getRecordAt() {
        return recordAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abnormal_data.record_at
     *
     * @param recordAt the value for abnormal_data.record_at
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setRecordAt(Long recordAt) {
        this.recordAt = recordAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abnormal_data.handle_at
     *
     * @return the value of abnormal_data.handle_at
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public Long getHandleAt() {
        return handleAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abnormal_data.handle_at
     *
     * @param handleAt the value for abnormal_data.handle_at
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setHandleAt(Long handleAt) {
        this.handleAt = handleAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abnormal_data.abnormal_date
     *
     * @return the value of abnormal_data.abnormal_date
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public Date getAbnormalDate() {
        return abnormalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abnormal_data.abnormal_date
     *
     * @param abnormalDate the value for abnormal_data.abnormal_date
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setAbnormalDate(Date abnormalDate) {
        this.abnormalDate = abnormalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abnormal_data.process_date
     *
     * @return the value of abnormal_data.process_date
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public Date getProcessDate() {
        return processDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abnormal_data.process_date
     *
     * @param processDate the value for abnormal_data.process_date
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setProcessDate(Date processDate) {
        this.processDate = processDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abnormal_data.process_user_id
     *
     * @return the value of abnormal_data.process_user_id
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public String getProcessUserId() {
        return processUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abnormal_data.process_user_id
     *
     * @param processUserId the value for abnormal_data.process_user_id
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setProcessUserId(String processUserId) {
        this.processUserId = processUserId == null ? null : processUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abnormal_data.process_reason
     *
     * @return the value of abnormal_data.process_reason
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public String getProcessReason() {
        return processReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abnormal_data.process_reason
     *
     * @param processReason the value for abnormal_data.process_reason
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setProcessReason(String processReason) {
        this.processReason = processReason == null ? null : processReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abnormal_data.created_at
     *
     * @return the value of abnormal_data.created_at
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abnormal_data.created_at
     *
     * @param createdAt the value for abnormal_data.created_at
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abnormal_data.updated_at
     *
     * @return the value of abnormal_data.updated_at
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abnormal_data.updated_at
     *
     * @param updatedAt the value for abnormal_data.updated_at
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}