package com.mingrui.flux.pojo;

import java.util.Date;

public class AlarmMsg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_msg.id
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_msg.mn
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    private String mn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_msg.created_at
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_msg.updated_at
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_msg.device_type
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    private Byte deviceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_msg.msg_type
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    private String msgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_msg.acquit_at
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    private Long acquitAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_msg.owner
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_msg.content
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_msg.id
     *
     * @return the value of alarm_msg.id
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_msg.id
     *
     * @param id the value for alarm_msg.id
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_msg.mn
     *
     * @return the value of alarm_msg.mn
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public String getMn() {
        return mn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_msg.mn
     *
     * @param mn the value for alarm_msg.mn
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setMn(String mn) {
        this.mn = mn == null ? null : mn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_msg.created_at
     *
     * @return the value of alarm_msg.created_at
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_msg.created_at
     *
     * @param createdAt the value for alarm_msg.created_at
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_msg.updated_at
     *
     * @return the value of alarm_msg.updated_at
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_msg.updated_at
     *
     * @param updatedAt the value for alarm_msg.updated_at
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_msg.device_type
     *
     * @return the value of alarm_msg.device_type
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public Byte getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_msg.device_type
     *
     * @param deviceType the value for alarm_msg.device_type
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setDeviceType(Byte deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_msg.msg_type
     *
     * @return the value of alarm_msg.msg_type
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_msg.msg_type
     *
     * @param msgType the value for alarm_msg.msg_type
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setMsgType(String msgType) {
        this.msgType = msgType == null ? null : msgType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_msg.acquit_at
     *
     * @return the value of alarm_msg.acquit_at
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public Long getAcquitAt() {
        return acquitAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_msg.acquit_at
     *
     * @param acquitAt the value for alarm_msg.acquit_at
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setAcquitAt(Long acquitAt) {
        this.acquitAt = acquitAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_msg.owner
     *
     * @return the value of alarm_msg.owner
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_msg.owner
     *
     * @param owner the value for alarm_msg.owner
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_msg.content
     *
     * @return the value of alarm_msg.content
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_msg.content
     *
     * @param content the value for alarm_msg.content
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}