package com.mingrui.flux.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class DataDetectorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public DataDetectorExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMessageIsNull() {
            addCriterion("message is null");
            return (Criteria) this;
        }

        public Criteria andMessageIsNotNull() {
            addCriterion("message is not null");
            return (Criteria) this;
        }

        public Criteria andMessageEqualTo(String value) {
            addCriterion("message =", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotEqualTo(String value) {
            addCriterion("message <>", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageGreaterThan(String value) {
            addCriterion("message >", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageGreaterThanOrEqualTo(String value) {
            addCriterion("message >=", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageLessThan(String value) {
            addCriterion("message <", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageLessThanOrEqualTo(String value) {
            addCriterion("message <=", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageLike(String value) {
            addCriterion("message like", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotLike(String value) {
            addCriterion("message not like", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageIn(List<String> values) {
            addCriterion("message in", values, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotIn(List<String> values) {
            addCriterion("message not in", values, "message");
            return (Criteria) this;
        }

        public Criteria andMessageBetween(String value1, String value2) {
            addCriterion("message between", value1, value2, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotBetween(String value1, String value2) {
            addCriterion("message not between", value1, value2, "message");
            return (Criteria) this;
        }

        public Criteria andMnIsNull() {
            addCriterion("mn is null");
            return (Criteria) this;
        }

        public Criteria andMnIsNotNull() {
            addCriterion("mn is not null");
            return (Criteria) this;
        }

        public Criteria andMnEqualTo(String value) {
            addCriterion("mn =", value, "mn");
            return (Criteria) this;
        }

        public Criteria andMnNotEqualTo(String value) {
            addCriterion("mn <>", value, "mn");
            return (Criteria) this;
        }

        public Criteria andMnGreaterThan(String value) {
            addCriterion("mn >", value, "mn");
            return (Criteria) this;
        }

        public Criteria andMnGreaterThanOrEqualTo(String value) {
            addCriterion("mn >=", value, "mn");
            return (Criteria) this;
        }

        public Criteria andMnLessThan(String value) {
            addCriterion("mn <", value, "mn");
            return (Criteria) this;
        }

        public Criteria andMnLessThanOrEqualTo(String value) {
            addCriterion("mn <=", value, "mn");
            return (Criteria) this;
        }

        public Criteria andMnLike(String value) {
            addCriterion("mn like", value, "mn");
            return (Criteria) this;
        }

        public Criteria andMnNotLike(String value) {
            addCriterion("mn not like", value, "mn");
            return (Criteria) this;
        }

        public Criteria andMnIn(List<String> values) {
            addCriterion("mn in", values, "mn");
            return (Criteria) this;
        }

        public Criteria andMnNotIn(List<String> values) {
            addCriterion("mn not in", values, "mn");
            return (Criteria) this;
        }

        public Criteria andMnBetween(String value1, String value2) {
            addCriterion("mn between", value1, value2, "mn");
            return (Criteria) this;
        }

        public Criteria andMnNotBetween(String value1, String value2) {
            addCriterion("mn not between", value1, value2, "mn");
            return (Criteria) this;
        }

        public Criteria andAcquitAtIsNull() {
            addCriterion("acquit_at is null");
            return (Criteria) this;
        }

        public Criteria andAcquitAtIsNotNull() {
            addCriterion("acquit_at is not null");
            return (Criteria) this;
        }

        public Criteria andAcquitAtEqualTo(Long value) {
            addCriterion("acquit_at =", value, "acquitAt");
            return (Criteria) this;
        }

        public Criteria andAcquitAtNotEqualTo(Long value) {
            addCriterion("acquit_at <>", value, "acquitAt");
            return (Criteria) this;
        }

        public Criteria andAcquitAtGreaterThan(Long value) {
            addCriterion("acquit_at >", value, "acquitAt");
            return (Criteria) this;
        }

        public Criteria andAcquitAtGreaterThanOrEqualTo(Long value) {
            addCriterion("acquit_at >=", value, "acquitAt");
            return (Criteria) this;
        }

        public Criteria andAcquitAtLessThan(Long value) {
            addCriterion("acquit_at <", value, "acquitAt");
            return (Criteria) this;
        }

        public Criteria andAcquitAtLessThanOrEqualTo(Long value) {
            addCriterion("acquit_at <=", value, "acquitAt");
            return (Criteria) this;
        }

        public Criteria andAcquitAtIn(List<Long> values) {
            addCriterion("acquit_at in", values, "acquitAt");
            return (Criteria) this;
        }

        public Criteria andAcquitAtNotIn(List<Long> values) {
            addCriterion("acquit_at not in", values, "acquitAt");
            return (Criteria) this;
        }

        public Criteria andAcquitAtBetween(Long value1, Long value2) {
            addCriterion("acquit_at between", value1, value2, "acquitAt");
            return (Criteria) this;
        }

        public Criteria andAcquitAtNotBetween(Long value1, Long value2) {
            addCriterion("acquit_at not between", value1, value2, "acquitAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNull() {
            addCriterion("create_at is null");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNotNull() {
            addCriterion("create_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAtEqualTo(Long value) {
            addCriterion("create_at =", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotEqualTo(Long value) {
            addCriterion("create_at <>", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThan(Long value) {
            addCriterion("create_at >", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThanOrEqualTo(Long value) {
            addCriterion("create_at >=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThan(Long value) {
            addCriterion("create_at <", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThanOrEqualTo(Long value) {
            addCriterion("create_at <=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtIn(List<Long> values) {
            addCriterion("create_at in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotIn(List<Long> values) {
            addCriterion("create_at not in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtBetween(Long value1, Long value2) {
            addCriterion("create_at between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotBetween(Long value1, Long value2) {
            addCriterion("create_at not between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andFanStatusIsNull() {
            addCriterion("fan_status is null");
            return (Criteria) this;
        }

        public Criteria andFanStatusIsNotNull() {
            addCriterion("fan_status is not null");
            return (Criteria) this;
        }

        public Criteria andFanStatusEqualTo(String value) {
            addCriterion("fan_status =", value, "fanStatus");
            return (Criteria) this;
        }

        public Criteria andFanStatusNotEqualTo(String value) {
            addCriterion("fan_status <>", value, "fanStatus");
            return (Criteria) this;
        }

        public Criteria andFanStatusGreaterThan(String value) {
            addCriterion("fan_status >", value, "fanStatus");
            return (Criteria) this;
        }

        public Criteria andFanStatusGreaterThanOrEqualTo(String value) {
            addCriterion("fan_status >=", value, "fanStatus");
            return (Criteria) this;
        }

        public Criteria andFanStatusLessThan(String value) {
            addCriterion("fan_status <", value, "fanStatus");
            return (Criteria) this;
        }

        public Criteria andFanStatusLessThanOrEqualTo(String value) {
            addCriterion("fan_status <=", value, "fanStatus");
            return (Criteria) this;
        }

        public Criteria andFanStatusLike(String value) {
            addCriterion("fan_status like", value, "fanStatus");
            return (Criteria) this;
        }

        public Criteria andFanStatusNotLike(String value) {
            addCriterion("fan_status not like", value, "fanStatus");
            return (Criteria) this;
        }

        public Criteria andFanStatusIn(List<String> values) {
            addCriterion("fan_status in", values, "fanStatus");
            return (Criteria) this;
        }

        public Criteria andFanStatusNotIn(List<String> values) {
            addCriterion("fan_status not in", values, "fanStatus");
            return (Criteria) this;
        }

        public Criteria andFanStatusBetween(String value1, String value2) {
            addCriterion("fan_status between", value1, value2, "fanStatus");
            return (Criteria) this;
        }

        public Criteria andFanStatusNotBetween(String value1, String value2) {
            addCriterion("fan_status not between", value1, value2, "fanStatus");
            return (Criteria) this;
        }

        public Criteria andFilterStatusIsNull() {
            addCriterion("filter_status is null");
            return (Criteria) this;
        }

        public Criteria andFilterStatusIsNotNull() {
            addCriterion("filter_status is not null");
            return (Criteria) this;
        }

        public Criteria andFilterStatusEqualTo(String value) {
            addCriterion("filter_status =", value, "filterStatus");
            return (Criteria) this;
        }

        public Criteria andFilterStatusNotEqualTo(String value) {
            addCriterion("filter_status <>", value, "filterStatus");
            return (Criteria) this;
        }

        public Criteria andFilterStatusGreaterThan(String value) {
            addCriterion("filter_status >", value, "filterStatus");
            return (Criteria) this;
        }

        public Criteria andFilterStatusGreaterThanOrEqualTo(String value) {
            addCriterion("filter_status >=", value, "filterStatus");
            return (Criteria) this;
        }

        public Criteria andFilterStatusLessThan(String value) {
            addCriterion("filter_status <", value, "filterStatus");
            return (Criteria) this;
        }

        public Criteria andFilterStatusLessThanOrEqualTo(String value) {
            addCriterion("filter_status <=", value, "filterStatus");
            return (Criteria) this;
        }

        public Criteria andFilterStatusLike(String value) {
            addCriterion("filter_status like", value, "filterStatus");
            return (Criteria) this;
        }

        public Criteria andFilterStatusNotLike(String value) {
            addCriterion("filter_status not like", value, "filterStatus");
            return (Criteria) this;
        }

        public Criteria andFilterStatusIn(List<String> values) {
            addCriterion("filter_status in", values, "filterStatus");
            return (Criteria) this;
        }

        public Criteria andFilterStatusNotIn(List<String> values) {
            addCriterion("filter_status not in", values, "filterStatus");
            return (Criteria) this;
        }

        public Criteria andFilterStatusBetween(String value1, String value2) {
            addCriterion("filter_status between", value1, value2, "filterStatus");
            return (Criteria) this;
        }

        public Criteria andFilterStatusNotBetween(String value1, String value2) {
            addCriterion("filter_status not between", value1, value2, "filterStatus");
            return (Criteria) this;
        }

        public Criteria andEmissionsConcIsNull() {
            addCriterion("emissions_conc is null");
            return (Criteria) this;
        }

        public Criteria andEmissionsConcIsNotNull() {
            addCriterion("emissions_conc is not null");
            return (Criteria) this;
        }

        public Criteria andEmissionsConcEqualTo(BigDecimal value) {
            addCriterion("emissions_conc =", value, "emissionsConc");
            return (Criteria) this;
        }

        public Criteria andEmissionsConcNotEqualTo(BigDecimal value) {
            addCriterion("emissions_conc <>", value, "emissionsConc");
            return (Criteria) this;
        }

        public Criteria andEmissionsConcGreaterThan(BigDecimal value) {
            addCriterion("emissions_conc >", value, "emissionsConc");
            return (Criteria) this;
        }

        public Criteria andEmissionsConcGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("emissions_conc >=", value, "emissionsConc");
            return (Criteria) this;
        }

        public Criteria andEmissionsConcLessThan(BigDecimal value) {
            addCriterion("emissions_conc <", value, "emissionsConc");
            return (Criteria) this;
        }

        public Criteria andEmissionsConcLessThanOrEqualTo(BigDecimal value) {
            addCriterion("emissions_conc <=", value, "emissionsConc");
            return (Criteria) this;
        }

        public Criteria andEmissionsConcIn(List<BigDecimal> values) {
            addCriterion("emissions_conc in", values, "emissionsConc");
            return (Criteria) this;
        }

        public Criteria andEmissionsConcNotIn(List<BigDecimal> values) {
            addCriterion("emissions_conc not in", values, "emissionsConc");
            return (Criteria) this;
        }

        public Criteria andEmissionsConcBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("emissions_conc between", value1, value2, "emissionsConc");
            return (Criteria) this;
        }

        public Criteria andEmissionsConcNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("emissions_conc not between", value1, value2, "emissionsConc");
            return (Criteria) this;
        }

        public Criteria andGranuleConcIsNull() {
            addCriterion("granule_conc is null");
            return (Criteria) this;
        }

        public Criteria andGranuleConcIsNotNull() {
            addCriterion("granule_conc is not null");
            return (Criteria) this;
        }

        public Criteria andGranuleConcEqualTo(BigDecimal value) {
            addCriterion("granule_conc =", value, "granuleConc");
            return (Criteria) this;
        }

        public Criteria andGranuleConcNotEqualTo(BigDecimal value) {
            addCriterion("granule_conc <>", value, "granuleConc");
            return (Criteria) this;
        }

        public Criteria andGranuleConcGreaterThan(BigDecimal value) {
            addCriterion("granule_conc >", value, "granuleConc");
            return (Criteria) this;
        }

        public Criteria andGranuleConcGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("granule_conc >=", value, "granuleConc");
            return (Criteria) this;
        }

        public Criteria andGranuleConcLessThan(BigDecimal value) {
            addCriterion("granule_conc <", value, "granuleConc");
            return (Criteria) this;
        }

        public Criteria andGranuleConcLessThanOrEqualTo(BigDecimal value) {
            addCriterion("granule_conc <=", value, "granuleConc");
            return (Criteria) this;
        }

        public Criteria andGranuleConcIn(List<BigDecimal> values) {
            addCriterion("granule_conc in", values, "granuleConc");
            return (Criteria) this;
        }

        public Criteria andGranuleConcNotIn(List<BigDecimal> values) {
            addCriterion("granule_conc not in", values, "granuleConc");
            return (Criteria) this;
        }

        public Criteria andGranuleConcBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("granule_conc between", value1, value2, "granuleConc");
            return (Criteria) this;
        }

        public Criteria andGranuleConcNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("granule_conc not between", value1, value2, "granuleConc");
            return (Criteria) this;
        }

        public Criteria andHydrocarbonConcIsNull() {
            addCriterion("hydrocarbon_conc is null");
            return (Criteria) this;
        }

        public Criteria andHydrocarbonConcIsNotNull() {
            addCriterion("hydrocarbon_conc is not null");
            return (Criteria) this;
        }

        public Criteria andHydrocarbonConcEqualTo(BigDecimal value) {
            addCriterion("hydrocarbon_conc =", value, "hydrocarbonConc");
            return (Criteria) this;
        }

        public Criteria andHydrocarbonConcNotEqualTo(BigDecimal value) {
            addCriterion("hydrocarbon_conc <>", value, "hydrocarbonConc");
            return (Criteria) this;
        }

        public Criteria andHydrocarbonConcGreaterThan(BigDecimal value) {
            addCriterion("hydrocarbon_conc >", value, "hydrocarbonConc");
            return (Criteria) this;
        }

        public Criteria andHydrocarbonConcGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("hydrocarbon_conc >=", value, "hydrocarbonConc");
            return (Criteria) this;
        }

        public Criteria andHydrocarbonConcLessThan(BigDecimal value) {
            addCriterion("hydrocarbon_conc <", value, "hydrocarbonConc");
            return (Criteria) this;
        }

        public Criteria andHydrocarbonConcLessThanOrEqualTo(BigDecimal value) {
            addCriterion("hydrocarbon_conc <=", value, "hydrocarbonConc");
            return (Criteria) this;
        }

        public Criteria andHydrocarbonConcIn(List<BigDecimal> values) {
            addCriterion("hydrocarbon_conc in", values, "hydrocarbonConc");
            return (Criteria) this;
        }

        public Criteria andHydrocarbonConcNotIn(List<BigDecimal> values) {
            addCriterion("hydrocarbon_conc not in", values, "hydrocarbonConc");
            return (Criteria) this;
        }

        public Criteria andHydrocarbonConcBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("hydrocarbon_conc between", value1, value2, "hydrocarbonConc");
            return (Criteria) this;
        }

        public Criteria andHydrocarbonConcNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("hydrocarbon_conc not between", value1, value2, "hydrocarbonConc");
            return (Criteria) this;
        }

        public Criteria andVelocityIsNull() {
            addCriterion("velocity is null");
            return (Criteria) this;
        }

        public Criteria andVelocityIsNotNull() {
            addCriterion("velocity is not null");
            return (Criteria) this;
        }

        public Criteria andVelocityEqualTo(BigDecimal value) {
            addCriterion("velocity =", value, "velocity");
            return (Criteria) this;
        }

        public Criteria andVelocityNotEqualTo(BigDecimal value) {
            addCriterion("velocity <>", value, "velocity");
            return (Criteria) this;
        }

        public Criteria andVelocityGreaterThan(BigDecimal value) {
            addCriterion("velocity >", value, "velocity");
            return (Criteria) this;
        }

        public Criteria andVelocityGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("velocity >=", value, "velocity");
            return (Criteria) this;
        }

        public Criteria andVelocityLessThan(BigDecimal value) {
            addCriterion("velocity <", value, "velocity");
            return (Criteria) this;
        }

        public Criteria andVelocityLessThanOrEqualTo(BigDecimal value) {
            addCriterion("velocity <=", value, "velocity");
            return (Criteria) this;
        }

        public Criteria andVelocityIn(List<BigDecimal> values) {
            addCriterion("velocity in", values, "velocity");
            return (Criteria) this;
        }

        public Criteria andVelocityNotIn(List<BigDecimal> values) {
            addCriterion("velocity not in", values, "velocity");
            return (Criteria) this;
        }

        public Criteria andVelocityBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("velocity between", value1, value2, "velocity");
            return (Criteria) this;
        }

        public Criteria andVelocityNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("velocity not between", value1, value2, "velocity");
            return (Criteria) this;
        }

        public Criteria andTemperatureIsNull() {
            addCriterion("temperature is null");
            return (Criteria) this;
        }

        public Criteria andTemperatureIsNotNull() {
            addCriterion("temperature is not null");
            return (Criteria) this;
        }

        public Criteria andTemperatureEqualTo(BigDecimal value) {
            addCriterion("temperature =", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureNotEqualTo(BigDecimal value) {
            addCriterion("temperature <>", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureGreaterThan(BigDecimal value) {
            addCriterion("temperature >", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("temperature >=", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureLessThan(BigDecimal value) {
            addCriterion("temperature <", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureLessThanOrEqualTo(BigDecimal value) {
            addCriterion("temperature <=", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureIn(List<BigDecimal> values) {
            addCriterion("temperature in", values, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureNotIn(List<BigDecimal> values) {
            addCriterion("temperature not in", values, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("temperature between", value1, value2, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("temperature not between", value1, value2, "temperature");
            return (Criteria) this;
        }

        public Criteria andMoistureIsNull() {
            addCriterion("moisture is null");
            return (Criteria) this;
        }

        public Criteria andMoistureIsNotNull() {
            addCriterion("moisture is not null");
            return (Criteria) this;
        }

        public Criteria andMoistureEqualTo(BigDecimal value) {
            addCriterion("moisture =", value, "moisture");
            return (Criteria) this;
        }

        public Criteria andMoistureNotEqualTo(BigDecimal value) {
            addCriterion("moisture <>", value, "moisture");
            return (Criteria) this;
        }

        public Criteria andMoistureGreaterThan(BigDecimal value) {
            addCriterion("moisture >", value, "moisture");
            return (Criteria) this;
        }

        public Criteria andMoistureGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("moisture >=", value, "moisture");
            return (Criteria) this;
        }

        public Criteria andMoistureLessThan(BigDecimal value) {
            addCriterion("moisture <", value, "moisture");
            return (Criteria) this;
        }

        public Criteria andMoistureLessThanOrEqualTo(BigDecimal value) {
            addCriterion("moisture <=", value, "moisture");
            return (Criteria) this;
        }

        public Criteria andMoistureIn(List<BigDecimal> values) {
            addCriterion("moisture in", values, "moisture");
            return (Criteria) this;
        }

        public Criteria andMoistureNotIn(List<BigDecimal> values) {
            addCriterion("moisture not in", values, "moisture");
            return (Criteria) this;
        }

        public Criteria andMoistureBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("moisture between", value1, value2, "moisture");
            return (Criteria) this;
        }

        public Criteria andMoistureNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("moisture not between", value1, value2, "moisture");
            return (Criteria) this;
        }

        public Criteria andFlagIsNull() {
            addCriterion("flag is null");
            return (Criteria) this;
        }

        public Criteria andFlagIsNotNull() {
            addCriterion("flag is not null");
            return (Criteria) this;
        }

        public Criteria andFlagEqualTo(String value) {
            addCriterion("flag =", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotEqualTo(String value) {
            addCriterion("flag <>", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThan(String value) {
            addCriterion("flag >", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThanOrEqualTo(String value) {
            addCriterion("flag >=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThan(String value) {
            addCriterion("flag <", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThanOrEqualTo(String value) {
            addCriterion("flag <=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLike(String value) {
            addCriterion("flag like", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotLike(String value) {
            addCriterion("flag not like", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagIn(List<String> values) {
            addCriterion("flag in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotIn(List<String> values) {
            addCriterion("flag not in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagBetween(String value1, String value2) {
            addCriterion("flag between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotBetween(String value1, String value2) {
            addCriterion("flag not between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andFanCurrentIsNull() {
            addCriterion("fan_current is null");
            return (Criteria) this;
        }

        public Criteria andFanCurrentIsNotNull() {
            addCriterion("fan_current is not null");
            return (Criteria) this;
        }

        public Criteria andFanCurrentEqualTo(Float value) {
            addCriterion("fan_current =", value, "fanCurrent");
            return (Criteria) this;
        }

        public Criteria andFanCurrentNotEqualTo(Float value) {
            addCriterion("fan_current <>", value, "fanCurrent");
            return (Criteria) this;
        }

        public Criteria andFanCurrentGreaterThan(Float value) {
            addCriterion("fan_current >", value, "fanCurrent");
            return (Criteria) this;
        }

        public Criteria andFanCurrentGreaterThanOrEqualTo(Float value) {
            addCriterion("fan_current >=", value, "fanCurrent");
            return (Criteria) this;
        }

        public Criteria andFanCurrentLessThan(Float value) {
            addCriterion("fan_current <", value, "fanCurrent");
            return (Criteria) this;
        }

        public Criteria andFanCurrentLessThanOrEqualTo(Float value) {
            addCriterion("fan_current <=", value, "fanCurrent");
            return (Criteria) this;
        }

        public Criteria andFanCurrentIn(List<Float> values) {
            addCriterion("fan_current in", values, "fanCurrent");
            return (Criteria) this;
        }

        public Criteria andFanCurrentNotIn(List<Float> values) {
            addCriterion("fan_current not in", values, "fanCurrent");
            return (Criteria) this;
        }

        public Criteria andFanCurrentBetween(Float value1, Float value2) {
            addCriterion("fan_current between", value1, value2, "fanCurrent");
            return (Criteria) this;
        }

        public Criteria andFanCurrentNotBetween(Float value1, Float value2) {
            addCriterion("fan_current not between", value1, value2, "fanCurrent");
            return (Criteria) this;
        }

        public Criteria andPurCurrentIsNull() {
            addCriterion("pur_current is null");
            return (Criteria) this;
        }

        public Criteria andPurCurrentIsNotNull() {
            addCriterion("pur_current is not null");
            return (Criteria) this;
        }

        public Criteria andPurCurrentEqualTo(Float value) {
            addCriterion("pur_current =", value, "purCurrent");
            return (Criteria) this;
        }

        public Criteria andPurCurrentNotEqualTo(Float value) {
            addCriterion("pur_current <>", value, "purCurrent");
            return (Criteria) this;
        }

        public Criteria andPurCurrentGreaterThan(Float value) {
            addCriterion("pur_current >", value, "purCurrent");
            return (Criteria) this;
        }

        public Criteria andPurCurrentGreaterThanOrEqualTo(Float value) {
            addCriterion("pur_current >=", value, "purCurrent");
            return (Criteria) this;
        }

        public Criteria andPurCurrentLessThan(Float value) {
            addCriterion("pur_current <", value, "purCurrent");
            return (Criteria) this;
        }

        public Criteria andPurCurrentLessThanOrEqualTo(Float value) {
            addCriterion("pur_current <=", value, "purCurrent");
            return (Criteria) this;
        }

        public Criteria andPurCurrentIn(List<Float> values) {
            addCriterion("pur_current in", values, "purCurrent");
            return (Criteria) this;
        }

        public Criteria andPurCurrentNotIn(List<Float> values) {
            addCriterion("pur_current not in", values, "purCurrent");
            return (Criteria) this;
        }

        public Criteria andPurCurrentBetween(Float value1, Float value2) {
            addCriterion("pur_current between", value1, value2, "purCurrent");
            return (Criteria) this;
        }

        public Criteria andPurCurrentNotBetween(Float value1, Float value2) {
            addCriterion("pur_current not between", value1, value2, "purCurrent");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_detector
     *
     * @mbg.generated do_not_delete_during_merge Fri Jul 01 15:37:45 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}