package com.mingrui.flux.pojo;

import org.springframework.web.bind.annotation.ResponseBody;

import java.math.BigDecimal;

public class DataDetector {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_detector.id
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_detector.message
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_detector.mn
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    private String mn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_detector.acquit_at
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    private Long acquitAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_detector.create_at
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    private Long createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_detector.fan_status
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    private String fanStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_detector.filter_status
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    private String filterStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_detector.emissions_conc
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    private BigDecimal emissionsConc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_detector.granule_conc
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    private BigDecimal granuleConc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_detector.hydrocarbon_conc
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    private BigDecimal hydrocarbonConc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_detector.velocity
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    private BigDecimal velocity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_detector.temperature
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    private BigDecimal temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_detector.moisture
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    private BigDecimal moisture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_detector.flag
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    private String flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_detector.fan_current
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    private Float fanCurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_detector.pur_current
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    private Float purCurrent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_detector.id
     *
     * @return the value of data_detector.id
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_detector.id
     *
     * @param id the value for data_detector.id
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_detector.message
     *
     * @return the value of data_detector.message
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_detector.message
     *
     * @param message the value for data_detector.message
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_detector.mn
     *
     * @return the value of data_detector.mn
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public String getMn() {
        return mn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_detector.mn
     *
     * @param mn the value for data_detector.mn
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public void setMn(String mn) {
        this.mn = mn == null ? null : mn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_detector.acquit_at
     *
     * @return the value of data_detector.acquit_at
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public Long getAcquitAt() {
        return acquitAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_detector.acquit_at
     *
     * @param acquitAt the value for data_detector.acquit_at
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public void setAcquitAt(Long acquitAt) {
        this.acquitAt = acquitAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_detector.create_at
     *
     * @return the value of data_detector.create_at
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public Long getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_detector.create_at
     *
     * @param createAt the value for data_detector.create_at
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public void setCreateAt(Long createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_detector.fan_status
     *
     * @return the value of data_detector.fan_status
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public String getFanStatus() {
        return fanStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_detector.fan_status
     *
     * @param fanStatus the value for data_detector.fan_status
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public void setFanStatus(String fanStatus) {
        this.fanStatus = fanStatus == null ? null : fanStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_detector.filter_status
     *
     * @return the value of data_detector.filter_status
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public String getFilterStatus() {
        return filterStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_detector.filter_status
     *
     * @param filterStatus the value for data_detector.filter_status
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public void setFilterStatus(String filterStatus) {
        this.filterStatus = filterStatus == null ? null : filterStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_detector.emissions_conc
     *
     * @return the value of data_detector.emissions_conc
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public BigDecimal getEmissionsConc() {
        return emissionsConc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_detector.emissions_conc
     *
     * @param emissionsConc the value for data_detector.emissions_conc
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public void setEmissionsConc(BigDecimal emissionsConc) {
        this.emissionsConc = emissionsConc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_detector.granule_conc
     *
     * @return the value of data_detector.granule_conc
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public BigDecimal getGranuleConc() {
        return granuleConc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_detector.granule_conc
     *
     * @param granuleConc the value for data_detector.granule_conc
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public void setGranuleConc(BigDecimal granuleConc) {
        this.granuleConc = granuleConc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_detector.hydrocarbon_conc
     *
     * @return the value of data_detector.hydrocarbon_conc
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public BigDecimal getHydrocarbonConc() {
        return hydrocarbonConc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_detector.hydrocarbon_conc
     *
     * @param hydrocarbonConc the value for data_detector.hydrocarbon_conc
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public void setHydrocarbonConc(BigDecimal hydrocarbonConc) {
        this.hydrocarbonConc = hydrocarbonConc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_detector.velocity
     *
     * @return the value of data_detector.velocity
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public BigDecimal getVelocity() {
        return velocity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_detector.velocity
     *
     * @param velocity the value for data_detector.velocity
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public void setVelocity(BigDecimal velocity) {
        this.velocity = velocity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_detector.temperature
     *
     * @return the value of data_detector.temperature
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public BigDecimal getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_detector.temperature
     *
     * @param temperature the value for data_detector.temperature
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public void setTemperature(BigDecimal temperature) {
        this.temperature = temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_detector.moisture
     *
     * @return the value of data_detector.moisture
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public BigDecimal getMoisture() {
        return moisture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_detector.moisture
     *
     * @param moisture the value for data_detector.moisture
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public void setMoisture(BigDecimal moisture) {
        this.moisture = moisture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_detector.flag
     *
     * @return the value of data_detector.flag
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_detector.flag
     *
     * @param flag the value for data_detector.flag
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_detector.fan_current
     *
     * @return the value of data_detector.fan_current
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public Float getFanCurrent() {
        return fanCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_detector.fan_current
     *
     * @param fanCurrent the value for data_detector.fan_current
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public void setFanCurrent(Float fanCurrent) {
        this.fanCurrent = fanCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_detector.pur_current
     *
     * @return the value of data_detector.pur_current
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public Float getPurCurrent() {
        return purCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_detector.pur_current
     *
     * @param purCurrent the value for data_detector.pur_current
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    public void setPurCurrent(Float purCurrent) {
        this.purCurrent = purCurrent;
    }
}