package com.mingrui.flux.dao;

import com.mingrui.flux.pojo.AbnormalData;
import com.mingrui.flux.pojo.AbnormalDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AbnormalDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abnormal_data
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    long countByExample(AbnormalDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abnormal_data
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    int deleteByExample(AbnormalDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abnormal_data
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abnormal_data
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    int insert(AbnormalData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abnormal_data
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    int insertSelective(AbnormalData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abnormal_data
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    List<AbnormalData> selectByExample(AbnormalDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abnormal_data
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    AbnormalData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abnormal_data
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    int updateByExampleSelective(@Param("record") AbnormalData record, @Param("example") AbnormalDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abnormal_data
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    int updateByExample(@Param("record") AbnormalData record, @Param("example") AbnormalDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abnormal_data
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    int updateByPrimaryKeySelective(AbnormalData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abnormal_data
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    int updateByPrimaryKey(AbnormalData record);
}