package com.mingrui.flux.dao;

import com.mingrui.flux.pojo.AlarmMsg;
import com.mingrui.flux.pojo.AlarmMsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlarmMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_msg
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    long countByExample(AlarmMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_msg
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    int deleteByExample(AlarmMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_msg
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_msg
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    int insert(AlarmMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_msg
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    int insertSelective(AlarmMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_msg
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    List<AlarmMsg> selectByExample(AlarmMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_msg
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    AlarmMsg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_msg
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    int updateByExampleSelective(@Param("record") AlarmMsg record, @Param("example") AlarmMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_msg
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    int updateByExample(@Param("record") AlarmMsg record, @Param("example") AlarmMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_msg
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    int updateByPrimaryKeySelective(AlarmMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_msg
     *
     * @mbg.generated Fri Jul 01 14:44:38 CST 2022
     */
    int updateByPrimaryKey(AlarmMsg record);
}