package com.mingrui.flux.dao;

import com.mingrui.flux.pojo.DataDetector;
import com.mingrui.flux.pojo.DataDetectorExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface DataDetectorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    long countByExample(DataDetectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    int deleteByExample(DataDetectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    int insert(DataDetector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    int insertSelective(DataDetector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    List<DataDetector> selectByExample(DataDetectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    DataDetector selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    int updateByExampleSelective(@Param("record") DataDetector record, @Param("example") DataDetectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    int updateByExample(@Param("record") DataDetector record, @Param("example") DataDetectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    int updateByPrimaryKeySelective(DataDetector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_detector
     *
     * @mbg.generated Fri Jul 01 15:37:45 CST 2022
     */
    int updateByPrimaryKey(DataDetector record);
}